### ISSUE TITLE
Leaderboard UX

### ISSUE THREAD

**Issue by itsdanesh** [DIT113-V22/group-08#30]
As a player, I want to view the leaderboard, so that I can see the top players.

Acceptance criterias:
-You can navigate to the leaderboard screen from the home screen.
 <del>-the list is ordered and shows the top 10 player 
- the list is ordered and shows the top 5 player 
- <del>two different leaderboard UX .</del>
-<del> the user can swipe between the two different leaderboards.  </del>
  The player should be able to go back to the main page after visiting the leaderboard screen.

**Comment by itsdanesh** [comment]
We have decided to show top 5 players instead of top 10 players

**Comment by faisal1201** [comment]
This issue needs to be refactored because we decided to have a Recycler view in the Leaderboard. Conveniently, it can store a list of players and their score from the database with the help of a adapter class . Also, because we decided to have only one leaderboard.

**Comment by faisal1201** [comment]
After being refactored, the database setup pull request fixes this issue.
