### ISSUE TITLE
Exploration Mode Improvements

### ISSUE THREAD

**Issue by Dreia** [DIT113-V22/group-08#39]
As a player I would like to better explore the environment and interact with it. 
<del> For that, I would like to have an automatic elevator to move the car to an upper level.
Acceptance criteria: 
<del>
- <del> car is moved without falling down and placed on the upper platform in position, facing the race track forwards.
-<del> the action is performed within 10 seconds of requesting it by the player.
-<del> the movements and design of the elevator are coherent with its function.

Encountered some technical issues with this user story. The emulator doesn't support upwards or downwards movements of the car controlled by Arduino, so the options are: 1) make an emulator variant for our group, 2) negotiate with the original feature specification in order to bypas coding the upward or downward movement in Arduino.

**Comment by Dreia** [comment]
Updated the user story to be more in line with the demands of the stakeholders

**Comment by Dreia** [comment]
@restless-learner the vehicle modding that you did actually goes into Finish Line detection issue. It would be great if you created a pull request mentioning that issue.

**Comment by Quinstedt** [comment]
Make sure to add this <DE L> (without the space , should be "del" or "DEL")  to the part that will not be done
<del> example of  how it should look 

so that this issue can be closed and the acceptance criteria can be checked in the DoD

**Comment by Dreia** [comment]
The elevator feature was not implemented since there was no good way to do it with actual coding and we are not interested in other avenues for now.
