### ISSUE TITLE
App navigation tests

### ISSUE THREAD

**Issue by Quinstedt** [DIT113-V22/group-08#42]
As a Player I want to be confident that the app buttons related to the navigation in the app are taking me to the right place so that I can easy move around in the app without complications.

TODO:
Create UI test for the navigation button. 
To test: 
- [x] Make sure that the layouts are launched 
- [x] Make sure that the Buttons and images are displayed
- [ ] Buttons related to navigation ( For  example mainactivty EnterRace button takes us to Control Choice or that the escapeHash in the activities are taking the user to the right place)

Acceptance criteria: 
All test are passing in the Android CI in Github. The test should focus on the portrait mode of the app.

**Comment by Quinstedt** [comment]
I should have reopen the issue and close it again. But im connecting this two issue which are related with a tag.

**Comment by faisal1201** [comment]
The leaderboard test was updated in the database pull request
