### ISSUE TITLE
Add `.import` folder to .gitignore

### ISSUE THREAD

**Issue by RuthgerD** [DIT113-V22/group-08#49]
The .import folder inside the custom mod you all created should not be checked in to git as it really slows down bloats the repository and is not required for the mod to function.

Remove the folder and add it to the .gitignore so that future revisions don't add anymore bloat, sadly unless we do some surgery it will always stay in the history.

**Comment by Quinstedt** [comment]
@Dreia can you can a look at this please

**Comment by Quinstedt** [comment]
@RuthgerD does this commit solve the problem you have mentioned here?
I just added the text directly in the .gitignore file.

**Comment by RuthgerD** [comment]
Yes but you also need to delete the folder and commit that
