### ISSUE TITLE
Modding the Emulator

### ISSUE THREAD

**Issue by faisal1201** [DIT113-V22/group-08#5]
As a player, I would like to drive the virtual car in a game environment with a game strategy, guiding me in a fun way so that I know where I start from, where I need to go and what challenges are in the way. 
Acceptance criteria: There are specific markers similar to typical race markers for start and finish line and the markers are visible during the race according to the game strategy. The game strategy is enforced by artifacts like obstacles, slopes, bumps.

**Comment by Dreia** [comment]
Still to do:
- Sort out the physics of the terrain in Godot
- Fix camera position issue
- Fix issues on Windows

**Comment by Dreia** [comment]
The Island.zip file can be found [here](https://we.tl/t-x5GWHiH1JT)
