### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by safayoussef** [DIT113-V22/group-08#55]
As a player, I would like to see the time when i start playing until the end of the game , so that i know how much time has gone since i start the race.
Acceptance criteria:
i)  the timer will start in the app once the player starts the game and end the timer once the finish line is reached. And then store the duration of the player so that it can be sent to the server for processing

**Comment by Quinstedt** [comment]
Reopen this issue because we are adding the pause and remove buttons. 
This issue was created instead of reopening the previous one #6 which was a timer in the java server that has been deleted.
