### ISSUE TITLE
Timer for race

### ISSUE THREAD

**Issue by faisal1201** [DIT113-V22/group-08#6]
As a player, I would like to know the total duration of my race, so that I can improve my score on my next try. 
Acceptance criteria: 
i) The timestamp when the race starts and ends is stored on the server and subtracted to get the duration.
ii) The time gets displayed to the player after the race ends.

**Comment by Dreia** [comment]
We reopened this issue because we needed to add the possibility to pause and resume the game.

**Comment by faisal1201** [comment]
Please refer to issue #55 for the newly implemented timer in Android app. This issue was created to calculate the time in the server. But, we no longer have a server and this issue is no longer applicable.

**Comment by Quinstedt** [comment]
as Faisal says above, this issue should be connected with #55 it has been closes with the pull request above.
