### ISSUE TITLE
Extended car  movements

### ISSUE THREAD

**Issue by faisal1201** [DIT113-V22/group-08#8]
As a player, I would like to move the car in a more flexible way combining diagonal movement with basic directions, so that I can react rapidly to race conditions. 
Acceptance criteria: The car executes the appropriate diagonal movement.
                                 The car can have 8 orientation,where the car head points to 8 angles: 0,45,90,135,180,225,270,315.

**Comment by Quinstedt** [comment]
This issues updates #7 makes sure to add it to the description

**Comment by Quinstedt** [comment]
Both this pull request are improving the car movements and are related to this issue as well as #7.
